import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { draftKey, draftSignature, readDraft, writeDraft, savedDraftStillCurrent } from "../src/client/videosBatchStudio/draftStorage";
import { TaskList } from "../src/client/videosBatchStudio/TaskList";
import { parseAppRoute, buildTasksPath } from "../src/client/routes";
const data = new Map<string, string>();
const storage = { getItem: (key: string) => data.get(key) ?? null, setItem: (key: string, value: string) => { data.set(key, value); }, removeItem: (key: string) => { data.delete(key); } };
const a = draftKey("session-a", "screenplay"); const b = draftKey("session-b", "screenplay");
const source = { scenes: [{ title: "saved" }] };
const value = { scenes: [{ title: "unsaved changes" }] };
assert.equal(writeDraft(storage, a, { base: draftSignature(source), value }), true);
assert.deepEqual(readDraft(storage, a)?.value, value, "remount/reload storage retains unsaved work");
assert.equal(readDraft(storage, b), undefined, "another session cannot inherit the draft");
assert.equal(readDraft(storage, a)!.base, draftSignature(structuredClone(source)), "identity-only changes are not conflicts");
assert.notEqual(readDraft(storage, a)!.base, draftSignature(value), "server content changes require conflict handling");
const submitted = { base: "saved", value: "draft A", id: "request-A" };
const newer = { ...submitted, value: "draft B", id: "edit-B" };
assert.equal(savedDraftStillCurrent(submitted, submitted, submitted), true);
assert.equal(savedDraftStillCurrent(submitted, newer, newer), false, "typing during save must survive the response");
assert.equal(savedDraftStillCurrent(submitted, submitted, newer), false, "unmounted instance must not clear a remounted editor's changes");
assert.equal(writeDraft({ ...storage, setItem() { throw new Error("quota"); } }, a, { base: "", value }), false);
writeDraft(storage, a); assert.equal(readDraft(storage, a), undefined);
assert.deepEqual(parseAppRoute({ pathname: buildTasksPath() }), { view: "tasks", sessionId: "" });
assert.equal(parseAppRoute({ pathname: "/gallery" }).view, "gallery");
const markup = renderToStaticMarkup(<TaskList sessions={[{ id: "a", title: "未发布教案" } as any]} onSelect={() => {}} onCreate={() => {}} onGallery={() => {}} />);
assert(markup.includes("未发布教案") && markup.includes("继续任务") && markup.includes("教案草稿"));
console.log("ADR0003 workspace smoke passed: draft storage/isolation, conflicts, task routes and unpublished sessions");
